### ISSUE TITLE
Mesh

### ISSUE THREAD

**Issue by andydufresn** [jdgonzalezwork/tetrascatt_reproducibility#1]
Hello, thank you for sharing this method. After reading your paper and reviewing your code, I have a question about how the .mesh files in the Mesh folder were generated. I noticed that you mentioned the SALOME software in your paper, but I found that there is no option to export .mesh files in the SALOME software. I wonder if you could kindly answer this question. Thank you for your patience and attention, and I wish you success in your research.

**Comment by elavia** [comment]
Hi. The ".mesh" extension is associated to the GMF (Gamma Mesh Format) file format which SALOME can export (last option in the File/Export menu). Let me know if this solves your question.

**Comment by andydufresn** [comment]
Hi. Your advice solve my confusion.Thank you!Best washes to you!
